language: generic

script: bash ./deploy.sh

branches:
  only:
    - master

env:
  global:
  - ENCRYPTION_LABEL=189e52c2c347
  - COMMIT_AUTHOR_EMAIL=travis-ci@w3.org
  - ECHIDNA_CONFIG_URL="https://raw.githubusercontent.com/w3c/permissions/master/.echidna"
  - DECISION="https://lists.w3.org/Archives/Public/public-webappsec/2015Mar/0170.html"
  # Exports $TOKEN - the W3C Token needed by Echidna to auto-publish this spec
  # See: https://github.com/w3c/echidna/wiki/How-to-use-Echidna-with-ReSpec-and-GitHub#the-token
  - secure: SneznWMBm52ct+mFI6NAVrB8k/BjO/H/hjR1eB3tjPwF0vzpL5fnbD1mmlNmVJMTWMsSUfI917JotA+7lfwoWJuHwlq2WfzQ0ybfvtuqjo7LS22T5X8IFYmCyVNR5asbJha/LNhqUyGDsZlPBgbKK0hqTd8eWjjQTztnlSrorGM=

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data-urlencode "url=$ECHIDNA_CONFIG_URL" --data-urlencode "decision=$DECISION" --data-urlencode "token=$TOKEN"'
